apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  COHERE_API_KEY: {{ .Values.secrets.cohereApiKey | b64enc | quote }}
  NEON_DATABASE_URL: {{ .Values.secrets.neonDbUrl | b64enc | quote }}
  BETTER_AUTH_SECRET: {{ .Values.secrets.authSecret | b64enc | quote }}
